
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import CleanHandsSBTContractArtifactJson from './clean_hands_sbt_contract-CleanHandsSBT.json' with { type: 'json' };
export const CleanHandsSBTContractArtifact = loadContractArtifact(CleanHandsSBTContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract CleanHandsSBT;
 */
export class CleanHandsSBTContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, CleanHandsSBTContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, CleanHandsSBTContract.artifact, wallet) as Promise<CleanHandsSBTContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, owner: AztecAddressLike) {
    return new DeployMethod<CleanHandsSBTContract>(PublicKeys.default(), wallet, CleanHandsSBTContractArtifact, CleanHandsSBTContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, owner: AztecAddressLike) {
    return new DeployMethod<CleanHandsSBTContract>(publicKeys, wallet, CleanHandsSBTContractArtifact, CleanHandsSBTContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof CleanHandsSBTContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<CleanHandsSBTContract['methods'][M]>
  ) {
    return new DeployMethod<CleanHandsSBTContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      CleanHandsSBTContractArtifact,
      CleanHandsSBTContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return CleanHandsSBTContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'owner' | 'sbt_count' | 'sbts' | 'address_to_sbt_id' | 'nullifier_to_sbt_id'> {
      return {
        owner: {
      slot: new Fr(1n),
    },
sbt_count: {
      slot: new Fr(2n),
    },
sbts: {
      slot: new Fr(3n),
    },
address_to_sbt_id: {
      slot: new Fr(4n),
    },
nullifier_to_sbt_id: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'owner' | 'sbt_count' | 'sbts' | 'address_to_sbt_id' | 'nullifier_to_sbt_id'>;
    }
    

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(owner: struct) */
    constructor: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_owner() */
    get_owner: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sbt_by_address(addr: struct) */
    get_sbt_by_address: ((addr: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sbt_by_id(sbt_id: field) */
    get_sbt_by_id: ((sbt_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sbt_by_nullifier(action_nullifier: field) */
    get_sbt_by_nullifier: ((action_nullifier: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint(recipient: struct, action_id: field, action_nullifier: field, expiry: integer) */
    mint: ((recipient: AztecAddressLike, action_id: FieldLike, action_nullifier: FieldLike, expiry: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_log(_log_plaintext: struct, _tx_hash: field, _unique_note_hashes_in_tx: struct, _first_nullifier_in_tx: field, _recipient: struct) */
    process_log: ((_log_plaintext: { storage: FieldLike[], len: (bigint | number) }, _tx_hash: FieldLike, _unique_note_hashes_in_tx: { storage: FieldLike[], len: (bigint | number) }, _first_nullifier_in_tx: FieldLike, _recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** revoke(sbt_id: field) */
    revoke: ((sbt_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_owner(new_owner: struct) */
    set_owner: ((new_owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
